function conn = estimateConnection
% ESTIMATECONNECTION Estimates connection to Securities database
	conn = database('Securities', 'loadout', 'RDS.1PostgreSQL.1LoadOut', ...
					'Vendor','PostgreSQL', ...
					'Server', 'securities.cmcdafitdhnz.us-west-2.rds.amazonaws.com', ...
					'PortNumber', 5432);
end
