
function [groups, groupMatrix] = loadConstraints
% LOADCONSTRAINTS Loads all Constraints, which will be added
	groups = loadGroups;
	groupMatrix = loadGroupMatrix;
end

function groups = loadGroups
% LOADGROUPS
% LowerGroup <= GroupMatrix * Port <= UpperGroup
% obj = setGroups(obj,GroupMatrix,LowerGroup,UpperGroup) 
	conn = estimateConnection;
	query = strcat( ...
					'WITH portf AS (', ...
						'SELECT p.symbol', ...
							 ', p.shares AS shares', ...
							 ', qe.dt AS date', ...
							 ', qe.price AS price', ...
							 ', round(p.shares*qe.price, 2) AS amount', ...
						 ' FROM PIF_Portfolio p', ...
						 ' JOIN PIF_quotes qe USING (symbol)', ...
						 ' WHERE qe.dt = (SELECT MAX(dt) ', ...
										  ' FROM PIF_quotes ', ...
										 ' WHERE symbol = p.symbol)', ...
					')', ...
				   ' SELECT issuer', ...
						 ', sum(amount)/(SELECT SUM(amount) FROM portf) AS shares', ...
					 ' FROM portf RIGHT JOIN PIFs USING (symbol)', ...
					' GROUP BY issuer', ...
					' ORDER BY issuer;' ...
					);
	setdbprefs('DataReturnFormat','table');
	curs = exec(conn, query);
	curs = fetch(curs);
	groups = curs.Data;
	groups = groups.shares;
	groups(isnan(groups))=0;
	close(curs)
	close(conn)
end

function groupMatrix = loadGroupMatrix
% LOADGROUPMATRIX
% LowerGroup <= GroupMatrix * Port <= UpperGroup
% obj = setGroups(obj,GroupMatrix,LowerGroup,UpperGroup) 
	conn = estimateConnection;
	query = strcat( ...
					'SELECT issuer,', ...
					   ' symbol,', ...
					   ' CASE WHEN symbol=a.symbol THEN 1', ...
							' ELSE 0', ...
					   ' END AS "Alfa Capital",', ...
					   ' CASE WHEN symbol=r.symbol THEN 1', ...
							' ELSE 0', ...
					   ' END AS "Raiffeisen Capital",', ...
					   ' CASE WHEN symbol=s.symbol THEN 1', ...
							' ELSE 0', ...
					   ' END AS "Sberbank AM",', ...
					   ' CASE WHEN symbol=v.symbol THEN 1', ...
							' ELSE 0', ...
					   ' END AS "VTB Capital AM"', ...
					  ' FROM PIFs', ...
					  ' LEFT JOIN (SELECT issuer, symbol FROM PIFs WHERE issuer=''Alfa Capital'') a USING (issuer, symbol)', ...
					  ' LEFT JOIN (SELECT issuer, symbol FROM PIFs WHERE issuer=''Raiffeisen Capital'') r USING (issuer, symbol)', ...
					  ' LEFT JOIN (SELECT issuer, symbol FROM PIFs WHERE issuer=''Sberbank AM'') s USING (issuer, symbol)', ...
					  ' LEFT JOIN (SELECT issuer, symbol FROM PIFs WHERE issuer=''VTB Capital AM'') v USING (issuer, symbol)', ...
					 ' WHERE type=''open-end''', ...
					 ' ORDER BY issuer, symbol;' ...
					);
	setdbprefs('DataReturnFormat','table');
	curs = exec(conn, query);
	curs = fetch(curs);
	groupMatrix = curs.Data;
	groupMatrix = table2array(groupMatrix(:,3:6))';
	close(curs)
	close(conn)
end



